apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: rollouts-demo
spec:
  replicas: 1
  strategy:
    blueGreen:
      activeService: rollouts-demo-blue
      previewService: rollouts-demo-green
      autoPromotionEnabled: false
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: 349101008628.dkr.ecr.us-west-2.amazonaws.com/nginx:1.2
        resources:
          requests:
            memory: 32Mi
            cpu: 5m
